# Builder for Poetry, its sole task is to generate `requirements.txt`
FROM python:3.9.12-buster as builder
WORKDIR /usr/src/app

RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry export --without-hashes --format requirements.txt > requirements.txt

# Base image with non-python dependencies
FROM python:3.9.12-buster as app_base

# Install Chromium & Chromium driver for Selenium
RUN apt-get update -y && \
    apt-get install -y chromium chromium-driver

# Base image with python dependencies, generated by poetry in `builder`
FROM app_base as app_deps
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install -r requirements.txt

# Full image with all dependencies and the actual source code
FROM app_deps as app
WORKDIR /usr/src/app

COPY src/ .